### PR TITLE
Use .gitignore from github/gitignore

### PR DESCRIPTION
**Pull request by strugee**
See https://github.com/github/gitignore/blob/master/Node.gitignore.

### CODE REVIEW

**Comment by strugee** [comment]
@gr2m I disagree - I think there's almost never (literally never?) a situation where you'd want to check in e.g. coverage data. If someone chooses to later add coverage to their bootstrapped project, it'll already be in `.gitignore` for them, and they won't run the risk of forgetting to add it. Plus while I generally _strongly_ agree with

> The best code is the code you don’t add 👍

I feel like it doesn't really apply here because this isn't "code" and isn't actively making the codebase more complex?

That being said if you feel strongly about it I can amend this patch to cut out irrelevant things. There are still a lot of things in the patched file that are useful, like ignoring npm/yarn logs and such.

**Comment by gr2m** [comment]
> @gr2m I disagree - I think there's almost never (literally never?) a situation where you'd want to check in e.g. coverage data

I’m sorry @strugee I think there was a misunderstanding. I agree that you’d never want to commit coverage data. The point I wanted to make is to not add rules for things that don’t apply (yet).

> I can amend this patch to cut out irrelevant things

That would be great 👍 thanks a lot

**Comment by mose** [comment]
Honestly I rather think that the generated gitignore can include things that are generic the same way github creates generic gitignores.

I would rather just be in favor to merge that pull request as is.

**Comment by strugee** [comment]
> Honestly I rather think that the generated gitignore can include things that are generic the same way github creates generic gitignores.

This was my original thinking. Should I still amend the patch? Thanks for the ping by the way ;)

**Comment by gr2m** [comment]
I really don’t have strong opinions, if @mose prefers it that way, go ahead and merge :) I would prefer to remove the parts that are not relevant to the project, but won’t object merging 👍

**Comment by mose** [comment]
Cool! let's move on :+1:

**Pull request merged**
